name: Hilbert Curve

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install black mypy
    - name: Check formatting with black
      run: |
        # stop the build if any file does not adhere to black formatting rules
        black --check . --config ./pyproject.toml
    - name: Run type checking
      run: |
        mypy . --config-file ./mypy.ini
